# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dapistrano"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.add_runtime_dependency "capistrano", ["<= 2.15.5"]
  s.add_runtime_dependency "railsless-deploy"  
  s.authors = ["Chad Fennell", "David Naughton"]
  s.date = "2014-02-15"
  s.description = "Deploy a Drupal site by building from a Drush Make file for each release."
  s.email = ["libsys@gmail.com", "naughton@umn.edu"]
  s.executables = ["dapify"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/dapify",
    "dapistrano.gemspec",
    "lib/dapistrano.rb"
  ]
  s.homepage = "https://github.com/chadfennell/dapistrano"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Deploy Drupal with Capistrano and Drush Make"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

